[build]
  command = "pip install -r requirements.txt && python app.py"
  publish = "path/to/public/directory"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
